-- QLBH Supabase rebuild schema.
-- Source of truth: SOURCE_SYSTEM_SPEC.md from qlbh-cuong-phong.

create extension if not exists pgcrypto;

create type order_type as enum ('ONLINE', 'IN_STORE');
create type order_status as enum (
  'CREATED',
  'PACKAGED',
  'SHIPPING',
  'SHIPPED',
  'PAYMENT_PENDING',
  'COMPLETED',
  'CANCELLED'
);
create type inventory_transaction_type as enum ('IMPORT', 'EXPORT');
create type inventory_transaction_source as enum ('MANUAL', 'ORDER', 'ORDER_CANCEL');

create table product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint not null references product_categories(id) on delete restrict,
  warranty_months integer not null default 24 check (warranty_months > 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  variant_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table shipping_providers (
  id bigint generated by default as identity primary key,
  provider_name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table shipping_provider_shippers (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references shipping_providers(id) on delete cascade,
  shipper_name text not null,
  shipper_phone text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table inventory_transactions (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete restrict,
  product_name text not null,
  variant_name text,
  import_price numeric(18, 2),
  quantity numeric(18, 6) not null check (quantity > 0),
  transaction_type inventory_transaction_type not null,
  source inventory_transaction_source,
  source_id bigint,
  batch_code text,
  invoice_file text,
  import_transaction_id bigint references inventory_transactions(id) on delete restrict,
  transaction_date date not null default current_date,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table sales_orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  customer_name text not null,
  customer_address text,
  customer_phone text,
  order_date date not null default current_date,
  sale_date date not null default current_date,
  status order_status not null default 'CREATED',
  order_type order_type not null,
  note text,
  sub_total numeric(18, 2) not null default 0 check (sub_total >= 0),
  discount_amount numeric(18, 2) not null default 0 check (discount_amount >= 0),
  extra_cost_total numeric(18, 2) not null default 0 check (extra_cost_total >= 0),
  shipping_fee numeric(18, 2) not null default 0 check (shipping_fee >= 0),
  total_amount numeric(18, 2) not null default 0 check (total_amount >= 0),
  estimated_cost_total numeric(18, 2) not null default 0 check (estimated_cost_total >= 0),
  projected_profit numeric(18, 2) not null default 0,
  shipping_provider_id bigint references shipping_providers(id) on delete restrict,
  shipping_provider_name text,
  shipper_name text,
  shipper_phone text,
  actual_shipping_fee numeric(18, 2),
  additional_cost numeric(18, 2),
  actual_profit numeric(18, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table sales_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references sales_orders(id) on delete cascade,
  product_id bigint references products(id) on delete restrict,
  product_name text not null,
  variant_name text not null,
  import_transaction_id bigint references inventory_transactions(id) on delete restrict,
  import_transaction_date date,
  import_unit_price numeric(18, 2),
  quantity numeric(18, 6) not null check (quantity > 0),
  sellable_quantity numeric(18, 6) not null default 0,
  unit_sale_price numeric(18, 2) not null check (unit_sale_price >= 0),
  discount_amount numeric(18, 2) not null default 0 check (discount_amount >= 0),
  warranty_months integer not null check (warranty_months > 0),
  line_total numeric(18, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table sales_order_extra_costs (
  id bigint generated by default as identity primary key,
  order_id bigint not null references sales_orders(id) on delete cascade,
  cost_name text not null,
  amount numeric(18, 2) not null check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table sales_order_shipping_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references sales_orders(id) on delete cascade,
  status order_status not null,
  changed_at timestamptz not null default now(),
  note text
);

create table sale_records (
  id bigint generated by default as identity primary key,
  product_name text,
  import_date date,
  import_price numeric(18, 2),
  sale_price numeric(18, 2),
  shipping_fee numeric(18, 2),
  sale_date date,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_products_category_id on products(category_id);
create index idx_product_variants_product_id on product_variants(product_id);
create index idx_inventory_product_variant on inventory_transactions(product_id, lower(coalesce(variant_name, '')));
create index idx_inventory_type_source on inventory_transactions(transaction_type, source);
create index idx_inventory_import_transaction_id on inventory_transactions(import_transaction_id);
create index idx_inventory_transaction_date on inventory_transactions(transaction_date);
create index idx_sales_orders_status_type on sales_orders(status, order_type);
create index idx_sales_orders_sale_date on sales_orders(sale_date);
create index idx_sales_orders_shipping_provider_id on sales_orders(shipping_provider_id);
create index idx_sales_order_items_order_id on sales_order_items(order_id);
create index idx_sales_order_items_product_variant on sales_order_items(product_id, lower(variant_name));
create index idx_sales_order_items_import_transaction_id on sales_order_items(import_transaction_id);
create index idx_shipping_provider_shippers_provider_id on shipping_provider_shippers(provider_id);

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_product_categories_updated_at before update on product_categories
for each row execute function set_updated_at();
create trigger trg_products_updated_at before update on products
for each row execute function set_updated_at();
create trigger trg_product_variants_updated_at before update on product_variants
for each row execute function set_updated_at();
create trigger trg_inventory_transactions_updated_at before update on inventory_transactions
for each row execute function set_updated_at();
create trigger trg_sales_orders_updated_at before update on sales_orders
for each row execute function set_updated_at();
create trigger trg_sales_order_items_updated_at before update on sales_order_items
for each row execute function set_updated_at();
create trigger trg_sales_order_extra_costs_updated_at before update on sales_order_extra_costs
for each row execute function set_updated_at();
create trigger trg_shipping_providers_updated_at before update on shipping_providers
for each row execute function set_updated_at();
create trigger trg_shipping_provider_shippers_updated_at before update on shipping_provider_shippers
for each row execute function set_updated_at();
create trigger trg_sale_records_updated_at before update on sale_records
for each row execute function set_updated_at();
